version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3031:3031"
    volumes:
      - ./backend/src:/app/backend/src
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend\src:/app/frontend/src
    environment:
      - NODE_ENV=development
